### ISSUE TITLE
Anzeige von "More Videos" wenn pausiert

### ISSUE THREAD

**Issue by operatorone** [heimrichhannot/contao-youtube#3]
Kann man auch deaktivieren, dass das Karussell von "More Videos" während der Pause angezeigt wird?

Siehe Screenshot https://ibb.co/jeKkvH

**Comment by fatcrobat** [comment]
Ja die Option ytShowRelated sollte dazu deaktiviert werden damit wird rel=0 der Iframe Url angefügt.

**Comment by operatorone** [comment]
Ich habe es wie im Screenshot zu sehen konfiguriert. Leider werden die ytShowRelated trotzdem eingeblendet. Oder habe ich da etwas falsch verstanden?

https://ibb.co/cnLfec

**Comment by fatcrobat** [comment]
Bitte heimrichhannot/contao-haste_plus auf Version 1.9.12 und heimrichhannot/contao-youtube auf Version 1.4.10 aktualisieren (oder einfach via composer update), hierbei handelte es sich um einen Fehler.

**Comment by operatorone** [comment]
Super. Hat geklappt! Vielen Dank :-)
