### ISSUE TITLE
Feature: Erweiterten Datenschutzmodus aktivieren

### ISSUE THREAD

**Issue by GMTeams** [heimrichhannot/contao-youtube#6]
Ich finde die Option des "privacy mode" schon recht gut, der user wird auf die Folgen aufmerksam gemacht.

Ich würde mir jedoch auch die Möglichkeit des von Youtube zur Verfügung gestellten "Erweiterten Datenschutzmodus" wünschen. Dies kann man beim erzeugen des Links zur Einbettung aktivieren, die URL wird umgeschrieben auf "youtube-nocookie.com".

**Comment by GMTeams** [comment]
Sorry, war etwas voreilig. Sobald man den "privacy mode" aktiviert, wird auch der "Erweiterte Datenschutzmodus" aktiviert.

Dann stellt sich mir jedoch eine andere Frage: Im "privacy mode" sieht man kein Thumbnail. Wahrscheinlich ist es nicht möglich eines zu zeigen bevor der User zustimmt?

Denn ich denke wenn der User gar nichts vom Video, sondern nur den Hinweis sieht, ist das schon eine recht große Hürde damit er es ansieht.

**Comment by fatcrobat** [comment]
Wir haben unseren privacy mode direkt mit www.youtube-nocookie.com verknüpft. 
Wenn kein Thumbnail angezeigt wird, dann muss du bitte einen API-Key [youtubeApiKey] in deb Systemeinstellungen hinterlegen. Wenn das Video privat ist, kann es sein, dass der Download des Bildes nicht möglich ist, dann kannst du aber ein eigenes Bild hinterlegen.
